version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - search-network
    env_file:
      - .env

  typesense:
    image: typesense/typesense:0.25.2
    container_name: typesense-server
    restart: always
    command: "--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors"
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    networks:
      - search-network
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  search-network:
    driver: bridge

volumes:
  pg_data:
  typesense_data:
